package week3.day2_1005.collection;

import java.util.ArrayList;
import java.util.List;

public class Names {

    public List<String> students = new ArrayList<>();
    public List<Student> studentObjs = new ArrayList<>();

    public List<Student> getStudentObjs() {
        this.studentObjs.add(new Student(1, "권하준", "https://github.com/dongyeon-0822/java-project-exercise"));
        this.studentObjs.add(new Student(1, "조성윤", "https://github.com/kang-subin/Java"));
        this.studentObjs.add(new Student(3, "안예은", "https://github.com/KoKwanwun/LikeLion.git"));
        this.studentObjs.add(new Student(1, "남우빈", "https://github.com/lcomment/Algorithm_Solution--Java/tree/main/LikeLion"));
        this.studentObjs.add(new Student(2, "최경민", "https://github.com/cmkxak/likelion-java-course"));
        this.studentObjs.add(new Student(3, "안준휘", "https://github.com/rnrudejr9/CodeLion-git-test"));
        this.studentObjs.add(new Student(2, "하채민", "https://github.com/Qkite/java-excercise-01/tree/main/src"));
        this.studentObjs.add(new Student(2, "허도한", "https://github.com/lucyoz/java-exercise"));
        this.studentObjs.add(new Student(2, "배태훈", "https://github.com/percyfrank/like-lion"));
        this.studentObjs.add(new Student(2, "정해성", "https://github.com/KimGunWoo9595/Lion_Java_Pratice"));
        this.studentObjs.add(new Student(2, "하찬희", "https://github.com/KimKiheon/LikeLion"));
        this.studentObjs.add(new Student(3, "박도아", "https://github.com/kny3037/java-exercise"));
        this.studentObjs.add(new Student(2, "유경준", "https://github.com/KimDohyoun79/remote_Lion.git"));
        this.studentObjs.add(new Student(1, "고다니엘", "https://github.com/kimkimj/create-repo1"));
        this.studentObjs.add(new Student(1, "하이안", "https://github.com/mingry2/intellij-git-exercise1"));
        this.studentObjs.add(new Student(1, "고유호", "https://github.com/Min-ji99/intelliJ-git-exercies"));
        this.studentObjs.add(new Student(2, "전민찬", "https://github.com/sangho527/Like_Lion_Java"));
        this.studentObjs.add(new Student(2, "배강", "https://github.com/ReadnThink/Like_lion.git"));
        this.studentObjs.add(new Student(3, "유서이", "https://github.com/yejinstar/git_exercise_push"));
        this.studentObjs.add(new Student(3, "황도빈", "https://github.com/dmdwns2/java-git-init"));
        this.studentObjs.add(new Student(2, "강규진", "https://github.com/Geuun/Java_Algorithm"));
        this.studentObjs.add(new Student(1, "임예린", "https://github.com/O-sulloc/java-exercise-1005"));
        this.studentObjs.add(new Student(2, "양예온", "https://github.com/chordpli/likelion_course"));
        this.studentObjs.add(new Student(2, "곽윤재", "https://github.com/strongcookdas/java.git"));
        this.studentObjs.add(new Student(1, "한단", "https://github.com/Kim-Ji-Yeong/Java-exercise"));
        this.studentObjs.add(new Student(2, "박강현", "https://github.com/k0605ja/git-test"));
        this.studentObjs.add(new Student(2, "윤성민", "https://github.com/pigeon2gugu/like-lion-2/tree/main/src/class_221005"));
        this.studentObjs.add(new Student(1, "박재윤", "https://github.com/hj-k66/git_exercise_2"));
        this.studentObjs.add(new Student(1, "서현준", "https://github.com/moomineee/JavaEx"));
        this.studentObjs.add(new Student(2, "노유주", "https://github.com/sujin-park0607/java-project-exercise"));
        this.studentObjs.add(new Student(3, "전율", "https://github.com/joypeb/java-project-push-test"));
        this.studentObjs.add(new Student(2, "노아린", "https://github.com/pi22-a/git_practice.git"));
        this.studentObjs.add(new Student(2, "권아윤", "https://github.com/JemJem70/Algolism/tree/master/src"));
        this.studentObjs.add(new Student(1, "송태서", "https://github.com/BearCrying/Git_Excercise/tree/main/src"));
        this.studentObjs.add(new Student(3, "정라온", "https://github.com/Bae-Ji-Won/Java-Study"));
        this.studentObjs.add(new Student(3, "서서한", "https://github.com/geunnseung/java_exercise_intellij_push.git"));
        this.studentObjs.add(new Student(3, "문주호", "https://github.com/JiMandy00/Java_LikeLion"));
        this.studentObjs.add(new Student(1, "오세아", "JAVA-GIT-TEST/src at main · seop93/JAVA-GIT-TEST (github.com)"));
        this.studentObjs.add(new Student(2, "이호영", "https://github.com/sjhlko/git-exercise-java"));
        this.studentObjs.add(new Student(3, "손윤아", "https://github.com/tgseo76/javja-ex"));
        this.studentObjs.add(new Student(3, "이동우", "https://github.com/seanee3670/CodeLion/tree/master/src"));
        this.studentObjs.add(new Student(2, "남혜준", "https://github.com/dalddu/Intellig-git-exercise"));
        this.studentObjs.add(new Student(1, "황솔", "https://github.com/hyunsik96/git-exercise-java-push"));
        this.studentObjs.add(new Student(1, "권은재", "https://github.com/ccodding/git-exercise-java-push"));
        this.studentObjs.add(new Student(1, "곽준휘", "https://github.com/TaylorSwiftlove/git-exercise-java"));
        this.studentObjs.add(new Student(1, "양시현", "https://github.com/jinwoooooo/git-exercise-java-push"));
        this.studentObjs.add(new Student(3, "김지훈", "https://github.com/simhyunbo/git-exercise-04.git"));
        this.studentObjs.add(new Student(3, "신서아", "https://github.com/ahngiwon00/git-exercise-java-push"));
        this.studentObjs.add(new Student(2, "노도형", "https://github.com/ahn-ji0/java_exercise"));
        this.studentObjs.add(new Student(3, "허선", "https://github.com/Changbum97/like-lion-java"));
        this.studentObjs.add(new Student(1, "노지아", "https://github.com/SoonMinEom/LikeALion"));
        this.studentObjs.add(new Student(3, "신아인", "https://github.com/ohy1023/newtest"));
        this.studentObjs.add(new Student(1, "양시은", "https://github.com/SuInWoo/LikeLion2th"));
        this.studentObjs.add(new Student(3, "노석현", ""));
        this.studentObjs.add(new Student(3, "손강준", "https://github.com/inkyu-yoon/IntelliJ_Commit_Test"));
        this.studentObjs.add(new Student(2, "백주안", "https://github.com/KaNoopy/like_lion.git"));
        this.studentObjs.add(new Student(1, "강단우", "https://github.com/ondayary/java-init-project.git"));
        this.studentObjs.add(new Student(2, "오나은", "https://github.com/dohyunre702/codelion_intelliJ"));
        this.studentObjs.add(new Student(1, "오한겸", "https://github.com/leejoonsang/bes2"));
        this.studentObjs.add(new Student(3, "백예준", "https://github.com/naegonggae/lion"));
        this.studentObjs.add(new Student(3, "노은우", "https://github.com/Soyeong4250/IntelliJPush"));
        this.studentObjs.add(new Student(1, "손도헌", "https://github.com/slrkajsep337/JavaStudy"));
        this.studentObjs.add(new Student(3, "전진우", "https://github.com/ajin0516/java_project.git"));
        this.studentObjs.add(new Student(2, "안주하", "https://github.com/yjyj1023/java-Calculator2"));
        this.studentObjs.add(new Student(3, "백다은", ""));
        this.studentObjs.add(new Student(1, "유민기", "https://github.com/hyeonju01/likelion_repo3_test/tree/main/src/week3/day2"));
        this.studentObjs.add(new Student(2, "노휘", "https://github.com/hakjun1/intelij-git-exercise03"));
        this.studentObjs.add(new Student(3, "박채원", "https://github.com/jangseoyun/Intellij-git-exercise"));
        this.studentObjs.add(new Student(2, "강다겸", "https://github.com/Senna97/git-exercise-java-push"));
        this.studentObjs.add(new Student(1, "신여준", "https://github.com/zinxeon/git-exercise-push"));
        this.studentObjs.add(new Student(3, "허은유", "https://github.com/su0545/like-lion-java.git"));
        this.studentObjs.add(new Student(2, "심서후", "https://github.com/Nickolodeon98/second-java-exercise"));
        this.studentObjs.add(new Student(3, "유준이", "https://github.com/daehwan0307/JAVA_Study"));
        this.studentObjs.add(new Student(1, "전민승", "https://github.com/sanghee2359?tab=repositories"));
        this.studentObjs.add(new Student(3, "강예은", "https://github.com/wogus0518/LikeLion-Backend"));
        this.studentObjs.add(new Student(1, "허로이", "https://github.com/heejunns/git_exercise_push.git"));
        this.studentObjs.add(new Student(2, "유유진", "https://github.com/h5000n/git-java-ex211005"));
        this.studentObjs.add(new Student(2, "권건하", "https://github.com/mooonju/java-exercise"));
        this.studentObjs.add(new Student(1, "하도이", "https://github.com/coastby/java-project"));
        this.studentObjs.add(new Student(2, "노도원", "https://github.com/Yunjaejo/new-project-push-test"));
        this.studentObjs.add(new Student(1, "문하성", "https://github.com/Combi153/BackEndSchool2"));
        this.studentObjs.add(new Student(1, "오시후", "https://github.com/chlalswns200/java_push"));
        this.studentObjs.add(new Student(3, "이로윤", "https://github.com/S2uJeong/git-exercise-java"));
        this.studentObjs.add(new Student(1, "노지후", "https://github.com/gemdoq/exercise"));
        this.studentObjs.add(new Student(2, "권채이", "https://github.com/surpmh/intellij-git-exercise"));
        this.studentObjs.add(new Student(3, "전담", "https://github.com/sandee-han/java-project-push-exercise"));
        this.studentObjs.add(new Student(3, "하태율", "https://github.com/JinDDung2/java-project/tree/main"));
        this.studentObjs.add(new Student(3, "노다율", "https://github.com/menuhwang/LikeLion"));
        this.studentObjs.add(new Student(1, "장우솔", "https://github.com/cvivis/git_practice2022/tree/main"));
        this.studentObjs.add(new Student(3, "황하준", "https://github.com/lay423/java-project"));
        return this.studentObjs;
    }
    public List<String> names() {
        this.students.add("권오석");
        this.students.add("권하준");
        this.students.add("조성윤");
        this.students.add("안예은");
        this.students.add("남우빈");
        this.students.add("최경민");
        this.students.add("안준휘");
        this.students.add("하채민");
        this.students.add("허도한");
        this.students.add("배태훈");
        this.students.add("정해성");
        this.students.add("하찬희");
        this.students.add("박도아");
        this.students.add("유경준");
        this.students.add("고다니");
        this.students.add("하이안");
        this.students.add("고유호");
        this.students.add("전민찬");
        this.students.add("배강");
        this.students.add("유서이");
        this.students.add("황도빈");
        this.students.add("강규진");
        this.students.add("임예린");
        this.students.add("양예온");
        this.students.add("곽윤재");
        this.students.add("한단 ");
        this.students.add("박강현");
        this.students.add("윤성민");
        this.students.add("박재윤");
        this.students.add("서현준");
        this.students.add("노유주");
        this.students.add("전율");
        this.students.add("노아린");
        this.students.add("권아윤");
        this.students.add("송태서");
        this.students.add("정라온");
        this.students.add("서서한");
        this.students.add("문주호");
        this.students.add("오세아");
        this.students.add("이호영");
        this.students.add("손윤아");
        this.students.add("이동우");
        this.students.add("남혜준");
        this.students.add("황솔");
        this.students.add("곽준휘");
        this.students.add("양시현");
        this.students.add("김지훈");
        this.students.add("신서아");
        this.students.add("노도형");
        this.students.add("허선");
        this.students.add("노지아");
        this.students.add("신아인");
        this.students.add("양시은");
        this.students.add("노석현");
        this.students.add("손강준");
        this.students.add("백주안");
        this.students.add("강단우");
        this.students.add("오나은");
        this.students.add("오한겸");
        this.students.add("백예준");
        this.students.add("노은우");
        this.students.add("손도헌");
        this.students.add("전진우");
        this.students.add("안주하");
        this.students.add("백다은");
        this.students.add("유민기");
        this.students.add("노휘");
        this.students.add("박채원");
        this.students.add("강다겸");
        this.students.add("신여준");
        this.students.add("허은유");
        this.students.add("심서후");
        this.students.add("유준이");
        this.students.add("전민승");
        this.students.add("강예은");
        this.students.add("허로이");
        this.students.add("유유진");
        this.students.add("권건하");
        this.students.add("하도이");
        this.students.add("노도원");
        this.students.add("문하성");
        this.students.add("오시후");
        this.students.add("이로윤");
        this.students.add("노지후");
        this.students.add("권채이");
        this.students.add("전담");
        this.students.add("하태율");
        this.students.add("노다율");
        this.students.add("장우솔");
        this.students.add("황하준");
        this.students.add("조담호");
        this.students.add("백민우");
        this.students.add("김시진");
        this.students.add("박유담");
        this.students.add("이해성");
        this.students.add("전현성");
        this.students.add("권유겸");
        this.students.add("강서현");
        this.students.add("문찬율");
        this.students.add("한도현");
        return this.students;
    }

}
